# install CouchDB by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure CouchDB

- name: Create couchdb directory
  file:
    path: /data/couchdb
    state: directory

- name: Configure CouchDB - enable remote connection
  lineinfile:
    path: /opt/couchdb/etc/default.ini
    regexp: 'bind_address = 127.0.0.1'
    line: 'bind_address = 0.0.0.0'
    firstmatch: yes
    backrefs: yes 

- name: Configure CouchDB - enable administrator password
  blockinfile:
    path: /opt/couchdb/etc/default.ini
    block: |
      [admins]
      {{couchdb_admin_username}} = {{couchdb_admin_password}}
    
- name: Enable CouchDB service
  service:
    name: couchdb
    state: started
    enabled: yes
     
# local.ini file needs to be created after CouchDB is started
- name: Configure CouchDB - auto create database
  lineinfile:
    dest: /opt/couchdb/etc/local.ini
    insertafter: '^[couchdb]'
    line: "single_node=true"
    
- name: Enable CouchDB service
  service:
    name: couchdb
    state: started
    enabled: yes
    
# set soft link, -b cover the exist links
# ln -sf src des
- name: set soft link
  shell: |
    ln -sf /opt/couchdb  /data/wwwroot/
    ln -sf /opt/couchdb/etc /data/config/couchdb 
    ln -sf /var/log/couchdb /data/logs/

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check CouchDB Version
    shell: sudo echo "couchdb version:" $(cat /data/wwwroot/couchdb/releases/*/couchdb.rel  |sed -n 3p | awk -F '"' '{print $4}') |sudo tee -a /data/logs/install_version.txt
  
  - name: Check CouchDB Service
    shell: systemctl status couchdb | grep Active*
    register: check_couchdb_service
    notify: check_couchdb_service
