# install CouchDB by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure CouchDB

- name: Create couchdb directory
  file:
    path: /data/couchdb
    state: directory

- name: Configure CouchDB - enable remote connection
  lineinfile:
    path: /opt/couchdb/etc/default.ini
    regexp: 'bind_address = 127.0.0.1'
    line: 'bind_address = 0.0.0.0'
    backrefs: yes 

- name: Configure CouchDB - enable administrator password
  blockinfile:
    path: /opt/couchdb/etc/default.ini
    block: |
      [admin]
      admin = {{couchdb_admin_password}}

- name: Enable CouchDB service
  service:
    name: couchdb
    state: started
    enabled: yes


# set soft link, -b cover the exist links
# ln -sb src des
- name: set soft link
  shell: |
    ln -sb /opt/couchdb  /data/couchdb 
    ln -sb /opt/couchdb/etc /data/config/couchdb 
    ln -sb /var/log/couchdb /data/logs/couchdb

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check CouchDB Version
    shell: sudo sh -c "/opt/couchdb/bin/couchdb -version 1>> /data/logs/install_version.txt"
  
  - name: Check CouchDB Service
    shell: systemctl status couchdb | grep Active*
    register: check_couchdb_service
    notify: check_couchdb_service
